language: swift
osx_image: xcode9.3beta
script:
  - xcodebuild -scheme MetaSerialization\ macOS -project MetaSerialization.xcodeproj build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
